# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.55.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym
    pilot
  end

  desc "Package a new version for adhoc distribution"
  lane :package do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end

  lane :upload do
    aws_s3(
      aws_profile: "hey_office",
      bucket: "hey-office-ios-releases",
      region: "ap-southeast-1",
      ipa: "build/HeyOffice.ipa",
      dsym: 'build/HeyOffice.app.dSYM.zip',
      html_template_path: 's3/index.html.erb'
    )
  end

  lane :get_apns_dev_certs do
    cryptex(type: "export", out: "apns_dev.p12", key: "apns_dev_p12")
    cryptex(type: "export", out: "apns_dev.pem", key: "apns_dev_pem")
    cryptex(type: "export", out: "apns_dev.pkey", key: "apns_dev_pkey")
  end

  lane :get_apns_prod_certs do
    cryptex(type: "export", out: "apns_dev.p12", key: "apns_dev_p12")
    cryptex(type: "export", out: "apns_dev.pem", key: "apns_dev_pem")
    cryptex(type: "export", out: "apns_dev.pkey", key: "apns_dev_pkey")
  end
end
